services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi
    env_file: .env.prod
    environment:
      SERVICE: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: worker
    env_file: .env.prod
    environment:
      SERVICE: worker
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
