"""currect user id type in notification table

Revision ID: ede2492a737f
Revises: f3b4d7f0db73
Create Date: 2026-02-08 19:25:10.066582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede2492a737f'
down_revision: Union[str, Sequence[str], None] = 'f3b4d7f0db73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'ACTIVE', 'INACTIVE', 'SUSPENDED', 'BANNED', name='userstatus'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.CHAR(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###
