"""db: update password field

Revision ID: bcb0802ce34c
Revises: c53c24debef1
Create Date: 2025-12-26 14:18:15.669173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "bcb0802ce34c"
down_revision: Union[str, Sequence[str], None] = "c53c24debef1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usermodel",
        sa.Column(
            "password", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    op.drop_column("usermodel", "password_hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usermodel", sa.Column("password_hash", sa.VARCHAR(length=255), nullable=False)
    )
    op.drop_column("usermodel", "password")
    # ### end Alembic commands ###
