from typing import Any, Protocol, runtime_checkable, Self


@runtime_checkable
class UnitOfWork(Protocol):
    events: list[Any]

    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type: Any, *_) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
